config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'
  get '/signup' ,to: 'users#new'
  post '/signup' ,to: 'users#create'
  resources :users
  get '/login' ,     to: 'sessions#new'
  post '/login' ,    to: 'sessions#create'
  delete '/logout' , to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end



  def create
  user = User.find_by(email: params[:session][:email].downcase)
  if user && user.authenticate(params[:session][:password])
    log_in user
    redirect_to user
  else
    flash.now[:danger] = 'Invalid email/password combination'
    render 'new'
  end
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "welcome"
      redirect_to @user
    else
      render 'new'
    end
  end
  def show
    @user = User.find(params[:id])
  end


  private

  def user_params
    params.require(:user).permit(:name , :email , :password , :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Artist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="container">
  <h1>Sign up</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user, url: signup_path) do |f| %>
        <%= render 'shared/error_messages' %>
        <%= f.label :name %>
        <%= f.text_field :name , class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email , class: 'form-control'%>

        <%= f.label :password %>
        <%= f.password_field :password , class: 'form-control'%>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation , class: 'form-control'%>

        <%= f.submit "Create my account", class: "btn btn-primary form-control" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
hello this is users show page
welcome, <%= @user.name %>







<div class="container space">

<div class="row">
  <div class="col-sm-6">
    <p class="welcome">Welcome</p>
    <p><%= @user.email  %></p>
  </div>
  <div class="col-sm-6">
    <p><%= @user.name  %>
  </div>


</div>


<div class="row">
  <h2>Your Favourite Artists</h2>
  <%# space for all comments and ratings %>

</div>
<div class="row">
  <div class="user"><%= link_to 'Edit Account', edit_user_path(@user) %></div>
  <div class="user"><%= link_to 'Delete Account', @user, method: :delete, data: { confirm: 'Are you sure?' } %></div>
</div>
</div>